### ISSUE TITLE
Adding unknown arguments after command not working

### ISSUE THREAD

**Issue by matystl** [ulrikstrid/reenv#19]
`reenv -e bf/.env ls -all` this return 
```
reenv: unknown option `-a'.
Usage: reenv [OPTION]... COMMAND [ARGS]...
Try `reenv --help' for more information.
```
My expectation was after i specify command in this case `ls` rest `-all` will be transparently passed to it.

**Comment by ulrikstrid** [comment]
This is definitely a bug, I'll look into it as soon as I can. Thanks for reporting it!

**Comment by ulrikstrid** [comment]
Actually, you have to do this to use flags `reenv -e .env -- ls --all`. There is no good way around it and `dotenv-cli` does the same thing so I feel like this is expected. I'll add it to the manual in a upcoming PR and close this.
