### ISSUE TITLE
Have dotenv-safe functionality

### ISSUE THREAD

**Issue by fakenickels** [ulrikstrid/reenv#3]
dotenv has a cousin called https://npmjs.com/package/dotenv-safe where you need to provide also a .env.example so it can check against that file and check if any declared var is missing

**Comment by fakenickels** [comment]
Just leaving the discussion here if you are interested in implementing this in reenv! Btw great tool 👏I was really looking for something like this implemented in native Reason

**Comment by ulrikstrid** [comment]
Seems like nice functionality to have, maybe could implement it under a flag `--safe .env.example`?

**Comment by fakenickels** [comment]
Looks really good for me

**Comment by ulrikstrid** [comment]
I have now added cmdliner and changed my internal representation so this should be pretty easy to add. Hopefully I can find some time the next couple of days.
